language: bash

dist: bionic

before_install:
    - curl -sf https://test.docker.com | sh
    - docker --version
  
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  matrix:
    - VARIANT=alpine
  
stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u sckyzo --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.8
  - docker buildx create --use
  - docker buildx build
    --platform $PLATFORMS
    --build-arg "OCTOPRINT_VERSION=$TRAVIS_BRANCH"
    --file "Dockerfile"
    --tag sckyzo/octoprint:$TRAVIS_BRANCH-$VARIANT
    `if [ -n "$TRAVIS_TAG" ] && [ "$VARIANT" = "alpine" ]; then echo "--tag sckyzo/octoprint:latest"; fi`
    `if [ "$VARIANT" = "alpine" ]; then echo "--tag sckyzo/octoprint:latest"; fi`
    --push
    .
  