version: '3'


services:
  octoprint:
    container_name: octoprint
    image: sckyzo/octoprint
    restart: unless-stopped
    environment:
      - CAMERA_DEV="/dev/video0"
      - MJPEG_STREAMER_AUTOSTART=true
      - MJPEG_STREAMER_INPUT="-y -n -f 30 -r 1280x720"
    ports:
      - 80:80
    volumes:
      - data:/data
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0


volumes:
    data:
